main_app/urls.py
from django.contrib import admin
from django.urls import path, include

# from debug_toolbar.toolbar import debug_toolbar_urls
from main_app import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('med_base.urls', namespace='med')),
    path('patients/', include('patients.urls', namespace='patients')),
    # namespace не является обязательным, если оно не задано, то будет использовано значение из app_name
]

if settings.DEBUG:
    # urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

med_base/urls.py
from django.urls import path
from . import views


app_name = 'med'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Шрифты -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">

    <title>{{ title }}</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css">
    <!-- Набор иконок -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static "img/favicon.ico" %}" type="image/x-icon">
</head>
<body>

    <div class="wrapper">
        <header class="wrapper__header">
            <!-- Сделано по шаблону Components-> Navbar -> 1 -->
            <div class="wrapper__navbar bg-info-subtle sticky-top">
                <!-- Добавлено из шаблона Components-> Navbar -> Color chemes -->
                <nav class="navbar navbar-expand-lg"  data-bs-theme="dark">
                    <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url "med:index" %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "patients:index" %}">Недавние пациенты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Раздел 2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "med:about" %}">О сайте</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "admin:index" %}">Админ</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Dropdown
                            </a>
                            <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                        </ul>
                    </div>
                    </div>
                </nav>
            </div>

            <!-- Сделано по шаблону Layout-> Grid -->
            <div class="wrapper__header__top container-fluid py-1">
                <div class="row">
                    <div class="col-sm-4">
                        <i class="fa-solid fa-mobile-screen"></i>
                        <a href="tel:+123456789">123-456-78-90</a>
                    </div>

                    <div class="col-sm-4 d-none d-sm-block d-flex justify-content-center align-items-center">
                        <ul class="social d-flex justify-content-center m-0 p-0">
                            <li><a href="#"><i class="fa-brands fa-telegram"></i></a></li>
                            <li class="mx-2"><a href="#"><i class="fa-brands fa-whatsapp"></i></a></li>
                            <li><a href="#"><i class="fa-solid fa-envelope-open-text"></i></a></li>
                        </ul>
                    </div>

                    <div class="col-sm-4 d-flex justify-content-end">
                        <div class="btn-group me-1">
                            <button class="btn btn-success dropdown-toggle btn-sm" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Аккаунт
                            </button>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="#">Войти</a></li>
                              <li><a class="dropdown-item" href="#">Выйти</a></li>
                              <li><a class="dropdown-item" href="#">Создать</a></li>
                            </ul>
                        </div>
                        <div class="btn-group">
                            <button class="btn btn-success dropdown-toggle btn-sm" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Выбрать язык
                            </button>
                            <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Русский</a></li>
                            <li><a class="dropdown-item" href="#">Английский</a></li>
                            <li><a class="dropdown-item" href="#">Испанский</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Сделано по шаблону Layout-> Grid -->
            <div class="wrapper__header__mid container-fluid bg-success p-2 text-dark bg-opacity-25">
                <div class="row">
                    <div class="col-6 col-md-4 logo">
                        <a href="#" class="h4 text-decoration-none link-success">Медсайт</a>
                    </div>

                    <div class="col-6 col-md-4 text-end order-md-2">
                        <!-- Сделано по шаблону Badge -> Positioned -->
                        <button type="button" class="btn btn-success btn-sm position-relative me-3" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample1" aria-controls="offcanvasExample1">
                            Результаты
                            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                              99+
                              <span class="visually-hidden">unread messages</span>
                            </span>
                        </button>

                        <!-- Сделано по шаблону Offcanvas -> Live demo -->
                        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasExample1" aria-labelledby="offcanvasExampleLabel">
                            <div class="offcanvas-header">
                              <h5 class="offcanvas-title" id="offcanvasExampleLabel">Результаты</h5>
                              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                            </div>
                            <div class="offcanvas-body">
                              <div>Здесь будут результаты анализов и исследований...</div>
                              <div class="dropdown mt-3">
                                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">
                                  Dropdown button
                                </button>
                                <ul class="dropdown-menu">
                                  <li><a class="dropdown-item" href="#">Action</a></li>
                                  <li><a class="dropdown-item" href="#">Another action</a></li>
                                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                                </ul>
                              </div>
                            </div>
                        </div>

                        <button type="button" class="btn btn-success btn-sm position-relative me-3" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample2" aria-controls="offcanvasExample2">
                            Вопросы
                            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                              99+
                              <span class="visually-hidden">unread messages</span>
                            </span>
                        </button>

                        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasExample2" aria-labelledby="offcanvasExampleLabel">
                            <div class="offcanvas-header">
                              <h5 class="offcanvas-title" id="offcanvasExampleLabel">Вопросы</h5>
                              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                            </div>
                            <div class="offcanvas-body">
                              <div>Здесь будут вопросы от пациентов...</div>
                              <div class="dropdown mt-3">
                                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">
                                  Dropdown button
                                </button>
                                <ul class="dropdown-menu">
                                  <li><a class="dropdown-item" href="#">Action</a></li>
                                  <li><a class="dropdown-item" href="#">Another action</a></li>
                                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                                </ul>
                              </div>
                            </div>
                        </div>

                    </div>

                    <!-- Сделано по шаблону Layout-> Columns -> Reordering -->
                    <!-- order-md-1 означает, что на экранах ≥768px этот элемент будет отображаться первым в своём flex-контейнере. -->
                    <div class="col-md-4 order-md-1 mt-2 mt-md-0">
                        <form action="">
                            <!-- Сделано по шаблону Forms -> Input group -->
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="ФИО пациента" aria-label="patientname" aria-describedby="button-addon2">
                                <button class="btn btn-outline-success" type="submit" id="button-addon2">
                                    <!-- Значок лупы из https://fontawesome.com/ -->
                                    <i class="fa-solid fa-magnifying-glass"></i></button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>

        </header>



        <!-- <main class="wrapper__main" style="padding-top: 170px;"> -->
        <main class="wrapper__main">
            <div class="container-fluid">
                <div id="content">
                    {% block content %}
                    {% endblock %}
                </div>

            </div>
        </main>

        <footer class="wrapper__footer">Футер</footer>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>